# Generated by Django 4.2.13 on 2024-05-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'profession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('getdate', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('sid', models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='basedb.student')),
                ('type', models.IntegerField()),
                ('cid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'evaluation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('sid', models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='basedb.student')),
                ('type', models.CharField(max_length=8)),
                ('infomation', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sc',
            fields=[
                ('sid', models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='basedb.student')),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc',
                'managed': False,
            },
        ),
    ]
